service: default
runtime: python312

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

env_variables:
  GCP_PROJECT_ID: "pro-groove-443318-s8"
  ENV: "PRO"
  CLOUD_SQL_CONNECTION_NAME: "pro-groove-443318-s8:europe-west1:brite-movies-db"

handlers:
  - url: /.*
    script: auto
